os: linux
sudo: required
language: cpp

services:
 - docker

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++-7-dev
    - g++-7
    update: true

cache:
  apt: true
  directories:
  - $HOME/.hunter

env: CC_EVAL=gcc-7 CXX_EVAL=g++-7

before_install:
- export CXX=$CXX_EVAL
- export CC=$CC_EVAL
- pip install --user cpplint
# - docker build -t alice_heroku . 
# - docker login -u $DOCKER_USER -p $DOCKER_PASS -e $DOCKER_EMAIL
# - docker push alice_heroku .

script:
- files=`find . -name "*.cpp" -or -name "*.hpp" -or -name ".h" | grep -v "./tools/*"`
# sanitaizer check
# - ./tools/polly/bin/polly --reconfig --toolchain sanitize-address --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold"
# clang-check
# - ./tools/polly/bin/polly --reconfig --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold" CMAKE_EXPORT_COMPILE_COMMANDS=ON
# tests
- export CTEST_OUTPUT_ON_FAILURE=true
# - ./tools/polly/bin/polly --reconfig --test --config Release --fwd CMAKE_EXE_LINKER="-fuse-ld=gold"


after_success:
  - heroku container:login
  - heroku container:push web -a $HEROKU_APP_NAME
  - heroku container:release web -a $HEROKU_APP_NAME

notifications:
  email: false

